#!/usr/bin/env python
# coding: utf-8

# In[140]:


import os
import glob
import pandas as pd
import numpy as np

os.chdir('/Users/rishi/Desktop/DAEN 690/indeed')


# In[141]:


extension = 'csv'
csv_file = [i for i in glob.glob('*.{}'.format(extension))]


# In[142]:


combined_csv = pd.concat([pd.read_csv(f) for f in csv_file ])
combined_csv.to_csv( "Job_posting_indeed.csv", index=False, encoding='utf-8-sig')


# In[143]:


indeed=pd.read_csv('Job_posting_indeed.csv')


# In[144]:


#delete the first column
del indeed['Unnamed: 0']     


# In[145]:


#method 1 for removinfg new from title
indeed['title'] = indeed['title'].str.lstrip('new')


# In[146]:


#method 2 for removing new from title
#   indeed['newcol']=np.where(indeed['title'].str[:3]=='new', indeed['title'].str[3:], indeed['title'])


# In[147]:


indeed.head()


# In[148]:


indeed.isnull().sum()


# In[149]:


indeed.info()


# In[150]:


indeed['Experience'] = np.random.randint(1, 8, indeed.shape[0])


# In[151]:


os.chdir('/Users/rishi/Desktop/DAEN 690/glassdoor')


# In[152]:


glassdoor=pd.read_csv('jobs.csv')


# In[153]:


del glassdoor['Rating']
del glassdoor['Headquarters']
del glassdoor['Size']
del glassdoor['Founded']
del glassdoor['Type of ownership']
del glassdoor['Industry']
del glassdoor['Sector']
del glassdoor['Revenue']
del glassdoor['Competitors']
del glassdoor['Easy Apply']


# In[154]:


glassdoor['Experience'] = np.random.randint(1, 8, glassdoor.shape[0])


# In[155]:


glassdoor.rename(columns={'Job Title': 'title', 'Salary Estimate': 'salary','Job Description':'summary','Company Name':'company','Location':'location'}, inplace=True)


# In[156]:


glassdoor.head()


# In[157]:


glassdoor['salary'] = glassdoor['salary'].str.rstrip(' (Glassdoor est.)')


# In[161]:


glassdoor['salary'] = glassdoor['salary'].str.rstrip('(Employ')


# In[162]:


glassdoor['salary']


# In[163]:


frame = [indeed,glassdoor]
total_data = pd.concat(frame)
total_data.head()


# In[164]:


total_data.to_csv('total_jobs.csv')


# In[ ]:



